language: node_js

node_js:
  - "node"

script: npm run build

before_deploy:
  - sed -i '/dist\/docs/d' .gitignore
  - sed -i '/dist\/app\*/d' .gitignore
  - sed -i '/index.html/d' .gitignore

deploy:
  - provider: releases
    skip_cleanup: true
    keep_history: true
    on:
      branch: master
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    keep_history: true
    on:
      branch: master
