language: node_js

node_js:
  - "node"

script: npm run build

before_deploy:
  - sed -i '/dist\/docs/d' .gitignore
  - sed -i '/dist\/app\*/d' .gitignore
  - sed -i '/index.html/d' .gitignore

deploy:
  - provider: releases
    api-key: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: true
    on:
      branch: master
  - provider: pages
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: true
    on:
      branch: master
