export { InstallationPage } from './Installation/InstallationPage'
export { ComponentPage } from './Component/ComponentPage'
export { ViewSyntaxPage } from './ViewSyntax/ViewSyntaxPage'
export { ReactivityPage } from './Reactivity/ReactivityPage'
export { RouterPage } from './Router/RouterPage'
export { MagicalAnimationsPage } from './MagicalAnimations/MagicalAnimationsPage'
export { WriterPage } from './Writer/WriterPage'
